In [1]:
from fastai.vision.all import *
from torchvision.transforms.functional import pil_to_tensor
import torchvision.transforms as T

/Users/smorrin/anaconda3/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Users/smorrin/anaconda3/lib/python3.11/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <CFED5F8E-EC3F-36FD-AAA3-2C6C7F8D3DD9> /Users/smorrin/anaconda3/lib/python3.11/site-packages/torchvision/image.so
  Expected in:     <2A8DB508-8AAF-3FF1-BDFE-9EF17CC2B482> /Users/smorrin/anaconda3/lib/python3.11/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [3]:
path = Path.cwd()  / "archive" / "train"; path

Path('/Users/smorrin/Coding/AI/DeforestationTUMAI/archive/train')

In [197]:
img_tens.shape

torch.Size([3, 2448, 2448])

In [198]:
om = pil_to_tensor(img)

In [199]:
om.shape

torch.Size([3, 96, 128])

In [200]:
om[0]

tensor([[ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        ...,
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17]], dtype=torch.uint8)

In [201]:
om[1]

tensor([[ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        ...,
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17]], dtype=torch.uint8)

In [202]:
om[2]

tensor([[ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        [ 4,  4,  4,  ..., 21, 21, 21],
        ...,
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17],
        [19, 19, 19,  ..., 17, 17, 17]], dtype=torch.uint8)

In [203]:
img_tp = img_tens.permute(1, 2, 0)

In [204]:
img_tp.to("mps")

tensor([[[  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255],
         ...,
         [  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255]],

        [[  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255],
         ...,
         [  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255]],

        [[  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255],
         ...,
         [  0,   0, 255],
         [  0,   0, 255],
         [  0,   0, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [205]:
replace_codes = tensor([
    [0, 255, 255],
    [255, 255, 0],
    [255, 0, 255],
    [0, 255, 0],
    [0, 0, 255],
    [255, 255, 255],
    [0, 0, 0]
], dtype=torch.uint8); replace_codes

tensor([[  0, 255, 255],
        [255, 255,   0],
        [255,   0, 255],
        [  0, 255,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]], dtype=torch.uint8)

In [206]:
for i in range(len(replace_codes)):
    replace_vec = replace_codes[i]
    bitmatrix = torch.all(img_tp == replace_vec, dim=2)
    img_tp[bitmatrix] = tensor([i] * 3, dtype=img_tp.dtype)

In [207]:
img_tp

tensor([[[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         ...,
         [4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        [[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         ...,
         [4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        [[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         ...,
         [4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        ...,

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         ...,
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         ...,
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         ...,
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]], dtype=torch.uint8)

In [208]:
img_or = img_tp.permute(2, 0, 1)

In [210]:
transform = T.ToPILImage()

In [211]:
img_or_p = transform(img_or)

In [212]:
img_or_p.show()

In [12]:
torch_device = "mps"
transform = T.ToPILImage()


def preprocess_image(path):
    pil_image = PILImage.create(path)
    img_tensor = pil_to_tensor(pil_image).to(torch_device)
    img_tensor = img_tensor.permute(1, 2, 0)
    replace_codes = tensor([
        [0, 255, 255],
        [255, 255, 0],
        [255, 0, 255],
        [0, 255, 0],
        [0, 0, 255],
        [255, 255, 255],
        [0, 0, 0]
    ], dtype=torch.uint8).to(torch_device)
    for i in range(len(replace_codes)):
        replace_vec = replace_codes[i]
        bitmatrix = torch.all(img_tensor == replace_vec, dim=2)
        img_tensor[bitmatrix] = tensor([i] * 3, dtype=img_tensor.dtype).to(torch_device)
    img_tensor = img_tensor.permute(2, 0, 1)
    pil_img = transform(img_tensor)
    return pil_img

In [13]:
img = preprocess_image(mask_path)

In [14]:
img.show()